---
version: 2
models:
- name: "model_FoobarTool2_a_process_geospatial_data"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__FoobarTool2_a"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mc0ls74f__FoobarTool2_a__process_geospatial_data"
    tags:
    - "prophecy_temp"
