---
version: 2
models:
- name: "model_ST_BufferTool_02_ST_BufferTool_02_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__ST_BufferTool_02"
  database: "andre_dev"
  schema: "alteryx_spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mcuql3z6__ST_BufferTool_02__ST_BufferTool_02_1"
    tags:
    - "prophecy_temp"
