---
version: 2
models:
- name: "model_ST_BufferTool_02_buffer_new_england"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__ST_BufferTool_02"
  database: "andre_dev"
  schema: "alteryx_spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mctugb3b__ST_BufferTool_02__buffer_new_england"
    tags:
    - "prophecy_temp"
