---
version: 2
models:
- name: "model_BufferTool_01_buffer_ne_polygons"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__BufferTool_01"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mc0fd8y9__BufferTool_01__buffer_ne_polygons"
    tags:
    - "prophecy_temp"
