---
version: 2
models:
- name: "model_UC_BufferTool_01_buffer_new_england"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__UC_BufferTool_01"
  database: "andre_dev"
  schema: "alteryx_spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mcwfmwvt__UC_BufferTool_01__buffer_new_england"
    tags:
    - "prophecy_temp"
