---
version: 2
models:
- name: "model_BufferTool_Old2_buffer_new_england"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__BufferTool_Old2"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mc51b9dn__BufferTool_Old2__buffer_new_england"
    tags:
    - "prophecy_temp"
