---
version: 2
models:
- name: "model_ST_BufferTool_ST_BufferTool_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__ST_BufferTool"
  database: "andre_dev"
  schema: "alteryx_spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mctlb76e__ST_BufferTool__ST_BufferTool_1"
    tags:
    - "prophecy_temp"
