---
version: 2
models:
- name: "model_MakeGridTool3_MakeGridTool3_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__MakeGridTool3"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mc9rbpv2__MakeGridTool3__MakeGridTool3_1"
    tags:
    - "prophecy_temp"
