---
version: 2
models:
- name: "model_MakeGridTool3_create_grid"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__MakeGridTool3"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mc0uvg3i__MakeGridTool3__create_grid"
    tags:
    - "prophecy_temp"
