---
version: 2
models:
- name: "model_GeneralizeTool_01_generalize_polygons"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__GeneralizeTool_01"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mcapyinq__GeneralizeTool_01__generalize_polygons"
    tags:
    - "prophecy_temp"
