---
version: 2
models:
- name: "model_Float_MakeGridTool_01_create_grid_from_polygons"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__Float_MakeGridTool_01"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mc0ssbk0__Float_MakeGridTool_01__create_grid_from_polygons"
    tags:
    - "prophecy_temp"
