---
version: 2
models:
- name: "model_MakeGridTool_04_MakeGridTool_04_0"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__MakeGridTool_04"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mc9r3qrm__MakeGridTool_04__MakeGridTool_04_0"
    tags:
    - "prophecy_temp"
