---
version: 2
models:
- name: "model_BufferTool_06_buffer_new_england"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__BufferTool_06"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mc9gre37__BufferTool_06__buffer_new_england"
    tags:
    - "prophecy_temp"
