---
version: 2
models:
- name: "model_BufferTableTool_BufferTableTool_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__BufferTableTool"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mccds0pd__BufferTableTool__BufferTableTool_1"
    tags:
    - "prophecy_temp"
