---
version: 2
models:
- name: "model_FoobarTool_process_ne_polygons"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__FoobarTool"
  database: "andre_dev"
  schema: "spatial"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mc0kfwgo__FoobarTool__process_ne_polygons"
    tags:
    - "prophecy_temp"
